version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    platform: linux/amd64

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
    ports:
      - '80:80'
